apiVersion: v1
kind: Pod
metadata:
  name: test-network-tools
  namespace: test-network
spec:
  containers:
  - name: tools
    image: busybox
    command:
    - sleep
    - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Never

