---
################################################################################
#
#   Orderer Configuration
#
################################################################################
General:
  ListenAddress: 0.0.0.0
  ListenPort: 6050
  TLS:
    Enabled: false
    PrivateKey: tls/server.key
    Certificate: tls/server.crt
    RootCAs:
      - tls/ca.crt
    ClientAuthRequired: false
    ClientRootCAs:
  Keepalive:
    ServerMinInterval: 60s
    ServerInterval: 7200s
    ServerTimeout: 20s
  Cluster:
    SendBufferSize: 10
    ClientCertificate:
    ClientPrivateKey:
    ListenPort:
    ListenAddress:
    ServerCertificate:
    ServerPrivateKey:
  BootstrapMethod: none
  BootstrapFile:
  LocalMSPDir: msp
  LocalMSPID: OrgMSP
  Profile:
    Enabled: false
    Address: 0.0.0.0:6060
  BCCSP:
    Default: SW
    SW:
      Hash: SHA2
      Security: 256
      FileKeyStore:
        KeyStore:
    PKCS11:
      Library:
      Label:
      Pin:
      Hash:
      Security:
      FileKeyStore:
        KeyStore:
  Authentication:
    TimeWindow: 15m

################################################################################
#
#   SECTION: File Ledger
#
################################################################################
FileLedger:
  Location: /var/hyperledger/production/orderer

################################################################################
#
#   SECTION: Kafka
#
################################################################################
Kafka:
  Retry:
    ShortInterval: 5s
    ShortTotal: 10m
    LongInterval: 5m
    LongTotal: 12h
    NetworkTimeouts:
      DialTimeout: 10s
      ReadTimeout: 10s
      WriteTimeout: 10s
    Metadata:
      RetryBackoff: 250ms
      RetryMax: 3
    Producer:
      RetryBackoff: 100ms
      RetryMax: 3
    Consumer:
      RetryBackoff: 2s
  Topic:
    ReplicationFactor: 3
  Verbose: false
  TLS:
    Enabled: false
    PrivateKey:
    Certificate:
    RootCAs:
  SASLPlain:
    Enabled: false
    User:
    Password:
  Version:

################################################################################
#
#   Debug Configuration
#
################################################################################
Debug:
  BroadcastTraceDir:
  DeliverTraceDir:

################################################################################
#
#   Operations Configuration
#
################################################################################
Operations:
  ListenAddress: 0.0.0.0:8443
  TLS:
    Enabled: false
    Certificate:
    PrivateKey:
    ClientAuthRequired: false
    ClientRootCAs: []

################################################################################
#
#   Metrics Configuration
#
################################################################################
Metrics:
  Provider: disabled
  Statsd:
    Network: udp
    Address: 127.0.0.1:8125
    WriteInterval: 30s
    Prefix:

################################################################################
#
#   Admin Configuration
#
################################################################################
Admin:
  ListenAddress: 0.0.0.0:9443
  TLS:
    Enabled: false
    Certificate:
    PrivateKey:
    ClientAuthRequired: true
    ClientRootCAs: []

################################################################################
#
#   Channel participation API Configuration
#
################################################################################
ChannelParticipation:
  Enabled: true
  MaxRequestBodySize: 1 MB

################################################################################
#
#   Consensus Configuration
#
################################################################################
Consensus:
  WALDir: /var/hyperledger/production/orderer/etcdraft/wal
  SnapDir: /var/hyperledger/production/orderer/etcdraft/snapshot

